name: ⚙️ Service 개발/수정 요청
description: Spring Backend Service 단위의 개발 또는 수정 작업을 위한 템플릿입니다.
title: "[Service] "
labels: ["backend", "feature"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Service 작업 요청
        새로운 Service 로직을 추가하거나 기존 로직을 수정할 때 작성합니다.

  - type: input
    id: service-name
    attributes:
      label: Service Name (Class/Method)
      description: 작업 대상 Service 클래스명 혹은 메서드명을 적어주세요.
      placeholder: ex) MemberService.join()
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 작업 개요 (Description)
      description: 이 Service가 수행해야 할 비즈니스 로직의 목적과 내용을 상세히 기술해주세요.
      placeholder: |
        - 회원 가입 시 중복 아이디 체크 로직을 수행합니다.
        - 비밀번호는 암호화하여 DB에 저장해야 합니다.
    validations:
      required: true

  - type: input
    id: api-endpoint
    attributes:
      label: 연관 API Endpoint (Optional)
      description: 이 Service와 연결되는 Controller의 엔드포인트가 있다면 적어주세요.
      placeholder: POST /api/v1/members/join
    validations:
      required: false

  - type: textarea
    id: technical-spec
    attributes:
      label: 기술 명세 (Technical Specs)
      description: DTO 구조, 트랜잭션 처리, Validation 등 기술적인 요구사항을 적어주세요.
      value: |
        ### Request DTO
        - Field: 
        
        ### Response DTO
        - Field: 
        
        ### Transaction & Exception
        - @Transactional(readOnly = false)
        - 예외 처리: 
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: 참고 자료 (References)
      description: 관련된 기획 문서, UI 디자인, 혹은 참고할 레퍼런스 링크를 첨부해주세요.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: 체크리스트 (Definition of Done)
      description: 작업 완료 조건을 체크해주세요.
      options:
        - label: 비즈니스 로직 구현 완료
        - label: Unit Test (JUnit/Mockito) 작성 및 통과
        - label: Swagger/API 문서 업데이트
        - label: 코드 리뷰 반영
